//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Betting_GAME {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Label a;
		
		protected System.Web.UI.WebControls.Label amount;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label colorRed;
		
		protected System.Web.UI.WebControls.Label colorGreen;
		
		protected System.Web.UI.WebControls.Label colorBlue;
		
		protected System.Web.UI.WebControls.Label colorYellow;
		
		protected System.Web.UI.WebControls.Label t;
		
		protected System.Web.UI.WebControls.Label total;
		
		protected System.Web.UI.WebControls.DropDownList numPlayers;
		
		protected System.Web.UI.WebControls.Panel player1Panel;
		
		protected System.Web.UI.WebControls.Label p1;
		
		protected System.Web.UI.WebControls.Button ButtonRed1;
		
		protected System.Web.UI.WebControls.Button ButtonGreen1;
		
		protected System.Web.UI.WebControls.Button ButtonBlue1;
		
		protected System.Web.UI.WebControls.Button ButtonYellow1;
		
		protected System.Web.UI.WebControls.Label a1;
		
		protected System.Web.UI.WebControls.Label p1i;
		
		protected System.Web.UI.WebControls.Panel player2Panel;
		
		protected System.Web.UI.WebControls.Label p2;
		
		protected System.Web.UI.WebControls.Button ButtonRed2;
		
		protected System.Web.UI.WebControls.Button ButtonGreen2;
		
		protected System.Web.UI.WebControls.Button ButtonBlue2;
		
		protected System.Web.UI.WebControls.Button ButtonYellow2;
		
		protected System.Web.UI.WebControls.Label a2;
		
		protected System.Web.UI.WebControls.Label p2i;
		
		protected System.Web.UI.WebControls.Panel player3Panel;
		
		protected System.Web.UI.WebControls.Label p3;
		
		protected System.Web.UI.WebControls.Button ButtonRed3;
		
		protected System.Web.UI.WebControls.Button ButtonGreen3;
		
		protected System.Web.UI.WebControls.Button ButtonBlue3;
		
		protected System.Web.UI.WebControls.Button ButtonYellow3;
		
		protected System.Web.UI.WebControls.Label a3;
		
		protected System.Web.UI.WebControls.Label p3i;
		
		protected System.Web.UI.WebControls.Panel player4Panel;
		
		protected System.Web.UI.WebControls.Label p4;
		
		protected System.Web.UI.WebControls.Button ButtonRed4;
		
		protected System.Web.UI.WebControls.Button ButtonGreen4;
		
		protected System.Web.UI.WebControls.Button ButtonBlue4;
		
		protected System.Web.UI.WebControls.Button ButtonYellow4;
		
		protected System.Web.UI.WebControls.Label a4;
		
		protected System.Web.UI.WebControls.Label p4i;
		
		protected System.Web.UI.WebControls.Button run_button;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl colorBox;
		
		protected System.Web.UI.WebControls.Label random_color;
		
		protected System.Web.UI.WebControls.Label colorLabel;
		
		protected System.Web.UI.WebControls.TextBox output_text;
	}
}
